# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mcapalbo <mcapalbo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/24 22:03:03 by mcapalbo          #+#    #+#              #
#    Updated: 2023/06/22 21:36:48 by mcapalbo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = get_next_line.c \
	ft_putstr.c \
	ft_isalpha.c	\
	ft_isdigit.c	\
	ft_isalnum.c	\
	ft_isascii.c	\
	ft_isprint.c	\
	ft_strlen.c	\
	ft_memset.c	\
	ft_bzero.c	\
	ft_memcpy.c	\
	ft_memmove.c	\
	ft_strlcpy.c	\
	ft_strlcat.c	\
	ft_toupper.c	\
	ft_tolower.c	\
	ft_strchr.c	\
	ft_strrchr.c	\
	ft_strncmp.c	\
	ft_memchr.c	\
	ft_memcmp.c	\
	ft_strnstr.c	\
	ft_atoi.c	\
	ft_calloc.c	\
	ft_strdup.c	\
	ft_substr.c	\
	ft_strjoin.c	\
	ft_strtrim.c	\
	ft_split.c	\
	ft_itoa.c	\
	ft_strmapi.c	\
	ft_striteri.c	\
	ft_putchar_fd.c	\
	ft_putstr_fd.c	\
	ft_putendl_fd.c	\
	ft_putnbr_fd.c	\

SRCBONUS = ft_lstnew.c	\
	ft_lstadd_front.c	\
	ft_lstsize.c	\
	ft_lstlast.c	\
	ft_lstadd_back.c	\
	ft_lstdelone.c	\
	ft_lstclear.c	\
	ft_lstiter.c	\
	ft_lstmap.c

OBJS = $(SRC:%.c=%.o)
OBJBONUS = $(SRCBONUS:%.c=%.o)
FLAGS = -Werror -Wextra -Wall


$(NAME):
	gcc $(FLAGS) -c $(SRC) -I.
	ar rcs $(NAME) $(OBJS)


all: $(NAME)


bonus : $(NAME)
	gcc -c $(FLAGS) $(SRCBONUS) -I.
	ar rcs $(NAME) $(OBJBONUS)

clean :
	rm -rf $(OBJS) $(OBJBONUS)


fclean : clean
	rm -f $(NAME)


re: fclean all


.PHONY: all clean clean bonus
